// Generated by QA-Core /generate
// User Story: "As a user, I want to add items to my shopping cart so that I can purchase them later."
// Generated: 2026-05-06

import { test, expect } from '@playwright/test';
import { InventoryPage } from '../pages/Inventory.page';
import { CartPage } from '../pages/Cart.page';

test.describe('Shopping Cart — Add Items', () => {

  test.beforeEach(async ({ page }) => {
    await page.goto('https://www.saucedemo.com/');
    await page.locator('[data-test="username"]').fill('standard_user');
    await page.locator('[data-test="password"]').fill('secret_sauce');
    await page.locator('[data-test="login-button"]').click();
    await expect(page).toHaveURL('/inventory.html');
  });

  // ─── Happy Path ───────────────────────────────────────────

  test('should add a single item to cart and update badge', async ({ page }) => {
    const inventory = new InventoryPage(page);
    await inventory.addFirstItemToCart();
    await expect(page.locator('.shopping_cart_badge')).toHaveText('1');
    await expect(inventory.firstAddButton).toHaveText('Remove');
  });

  test('should add multiple items and reflect correct count in badge', async ({ page }) => {
    const inventory = new InventoryPage(page);
    await inventory.addItemByIndex(0);
    await inventory.addItemByIndex(1);
    await inventory.addItemByIndex(2);
    await expect(page.locator('.shopping_cart_badge')).toHaveText('3');
  });

  // ─── Negative Scenarios ───────────────────────────────────

  test('should remove item from cart when Remove is clicked', async ({ page }) => {
    const inventory = new InventoryPage(page);
    await inventory.addFirstItemToCart();
    await inventory.removeFirstItemFromCart();
    await expect(page.locator('.shopping_cart_badge')).toBeHidden();
    await expect(inventory.firstAddButton).toHaveText('Add to cart');
  });

  test('should persist cart items after navigating away and returning', async ({ page }) => {
    const inventory = new InventoryPage(page);
    await inventory.addFirstItemToCart();
    await inventory.addItemByIndex(1);
    await page.goto('https://www.saucedemo.com/inventory-item.html?id=0');
    await page.goBack();
    await expect(page.locator('.shopping_cart_badge')).toHaveText('2');
  });

  // ─── Edge Cases ───────────────────────────────────────────

  test('should navigate to cart page when cart icon is clicked', async ({ page }) => {
    const inventory = new InventoryPage(page);
    await inventory.addFirstItemToCart();
    await page.locator('.shopping_cart_link').click();
    await expect(page).toHaveURL('/cart.html');
    await expect(page.locator('.cart_item')).toHaveCount(1);
  });

  test('should show empty state when cart has no items', async ({ page }) => {
    await page.goto('https://www.saucedemo.com/cart.html');
    await expect(page.locator('.cart_item')).toHaveCount(0);
    await expect(page.locator('[data-test="checkout"]')).toBeDisabled();
  });

});
