// Generated by QA-Core /explore https://www.saucedemo.com/
// Command: /explore https://www.saucedemo.com/
// Generated: 2026-05-06

import { test, expect } from '@playwright/test';
import { LoginPage } from '../pages/Login.page';

test.describe('Login Page — saucedemo.com', () => {

  let loginPage: LoginPage;

  test.beforeEach(async ({ page }) => {
    loginPage = new LoginPage(page);
    await loginPage.goto();
  });

  // ─── Happy Path ───────────────────────────────────────────

  test('should log in successfully with valid credentials', async ({ page }) => {
    await loginPage.login('standard_user', 'secret_sauce');
    await expect(page).toHaveURL('/inventory.html');
    await expect(page.locator('.inventory_list')).toBeVisible();
  });

  // ─── Negative Scenarios ───────────────────────────────────

  test('should show error when password is incorrect', async () => {
    await loginPage.login('standard_user', 'wrong_password');
    await expect(loginPage.errorMessage).toBeVisible();
    await expect(loginPage.errorMessage).toContainText('Username and password do not match');
  });

  test('should show error when username is empty', async () => {
    await loginPage.login('', 'secret_sauce');
    await expect(loginPage.errorMessage).toBeVisible();
    await expect(loginPage.errorMessage).toContainText('Username is required');
  });

  test('should show error when password is empty', async () => {
    await loginPage.login('standard_user', '');
    await expect(loginPage.errorMessage).toBeVisible();
    await expect(loginPage.errorMessage).toContainText('Password is required');
  });

  test('should show error for locked out user', async () => {
    await loginPage.login('locked_out_user', 'secret_sauce');
    await expect(loginPage.errorMessage).toBeVisible();
    await expect(loginPage.errorMessage).toContainText('Sorry, this user has been locked out');
  });

  // ─── Edge Cases ───────────────────────────────────────────

  test('should handle special characters in username gracefully', async () => {
    await loginPage.login('<script>alert(1)</script>', 'secret_sauce');
    await expect(loginPage.errorMessage).toBeVisible();
    // Ensure no XSS — error is plain text, not rendered HTML
    await expect(page.locator('script')).toHaveCount(0);
  });

});
