import fs from 'node:fs';
import path from 'node:path';
import { emitLocatorCall } from './selectors.js';
import type { Assertion, RunReport, Scenario, SelectorRecord, TraceStep } from './trace.js';

/**
 * Turn a verified trace into a runnable Playwright spec.
 *
 * Deterministic (no LLM) — every action in the spec corresponds 1:1 to an
 * action the agent already executed successfully against the live page.
 */

export interface TranscribeOptions {
  report: RunReport;
  outDir: string;
  /** File basename, no extension. */
  name: string;
}

export interface TranscribeResult {
  specPath: string;
  scenarios: number;
}

export function transcribe(opts: TranscribeOptions): TranscribeResult {
  const { report, outDir, name } = opts;
  fs.mkdirSync(outDir, { recursive: true });
  const ext = report.language;
  const file = `${name}.spec.${ext}`;
  const specPath = path.join(outDir, file);

  const lines: string[] = [];
  if (ext === 'ts') {
    lines.push(`import { test, expect } from '@playwright/test';`);
    lines.push(`import AxeBuilder from '@axe-core/playwright';`);
  } else {
    lines.push(`const { test, expect } = require('@playwright/test');`);
    lines.push(`const AxeBuilder = require('@axe-core/playwright').default;`);
  }
  lines.push('');
  lines.push(`/* Auto-generated by QA-Core. Source URL: ${report.url}`);
  lines.push(` * Scenarios were verified live before transcription.`);
  lines.push(` * Selectors prefer accessibility (role/label) over CSS — see report.cascadeStats.`);
  lines.push(` */`);
  lines.push('');
  lines.push(`test.describe(${q(titleFromUrl(report.url))}, () => {`);
  for (const scenario of report.scenarios) {
    emitScenario(lines, scenario, ext);
  }
  lines.push(emitA11ySpec(report.url, ext));
  lines.push('});');
  lines.push('');

  fs.writeFileSync(specPath, lines.join('\n'));
  return { specPath, scenarios: report.scenarios.length };
}

function emitScenario(lines: string[], scenario: Scenario, ext: 'ts' | 'js'): void {
  const params = ext === 'ts' ? '({ page })' : '({ page })';
  lines.push(`  test(${q(`${tag(scenario.category)} ${scenario.name}`)}, async ${params} => {`);
  for (const step of scenario.steps) {
    lines.push(...emitStep(step).map(l => `    ${l}`));
  }
  lines.push('  });');
  lines.push('');
}

function emitStep(step: TraceStep): string[] {
  switch (step.kind) {
    case 'navigate':
      return [`await page.goto(${q(step.url)});`];
    case 'click':
      return [`await ${loc(step.target)}.click();`];
    case 'fill':
      return [`await ${loc(step.target)}.fill(${q(step.value)});`];
    case 'press':
      return [`await ${loc(step.target)}.press(${q(step.key)});`];
    case 'wait':
      return [`await page.waitForTimeout(${step.ms});`];
    case 'assert':
      return emitAssertion(step.assertion);
    case 'checkpoint':
      return [`// — ${step.label}`];
  }
}

function emitAssertion(a: Assertion): string[] {
  switch (a.type) {
    case 'toBeVisible':
      return [`await expect(${loc(a.target)}).toBeVisible();`];
    case 'toHaveText':
      return [`await expect(${loc(a.target)}).toHaveText(${q(a.text)});`];
    case 'toContainText':
      return [`await expect(${loc(a.target)}).toContainText(${q(a.text)});`];
    case 'toHaveURL':
      return [`await expect(page).toHaveURL(new RegExp(${q(a.pattern)}));`];
    case 'toHaveCount':
      return [`await expect(${loc(a.target)}).toHaveCount(${a.count});`];
  }
}

function loc(record: SelectorRecord): string {
  return emitLocatorCall(record.level, record.arg);
}

function emitA11ySpec(url: string, ext: 'ts' | 'js'): string {
  // Auto-injected accessibility check on the landing page.
  const head = ext === 'ts' ? `  test('a11y: landing page has no detectable WCAG violations', async ({ page }) => {`
                            : `  test('a11y: landing page has no detectable WCAG violations', async ({ page }) => {`;
  return [
    head,
    `    await page.goto(${q(url)});`,
    `    const results = await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa']).analyze();`,
    `    expect(results.violations, JSON.stringify(results.violations, null, 2)).toEqual([]);`,
    `  });`,
  ].join('\n');
}

function tag(c: Scenario['category']): string {
  return c === 'happy' ? '[happy]' : c === 'negative' ? '[negative]' : c === 'edge' ? '[edge]' : '[a11y]';
}

function titleFromUrl(url: string): string {
  try {
    const u = new URL(url);
    return `QA-Core: ${u.host}${u.pathname === '/' ? '' : u.pathname}`;
  } catch {
    return `QA-Core: ${url}`;
  }
}

function q(s: string): string {
  return JSON.stringify(s);
}
